//
// File generated by rootcint at Wed May 26 22:00:02 2021

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIdisk2dIdatadItmnguyendItestroottreedIForStudentsdIdataClassesdIDataCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DataCint.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void RawEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_RawEvent(void *p = 0);
   static void *newArray_RawEvent(Long_t size, void *p);
   static void delete_RawEvent(void *p);
   static void deleteArray_RawEvent(void *p);
   static void destruct_RawEvent(void *p);
   static void streamer_RawEvent(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::RawEvent*)
   {
      ::RawEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::RawEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("RawEvent", ::RawEvent::Class_Version(), "/disk2/data/tmnguyen/testroottree/ForStudents/dataClasses/RawEvent.h", 26,
                  typeid(::RawEvent), ::ROOT::DefineBehavior(ptr, ptr),
                  &::RawEvent::Dictionary, isa_proxy, 0,
                  sizeof(::RawEvent) );
      instance.SetNew(&new_RawEvent);
      instance.SetNewArray(&newArray_RawEvent);
      instance.SetDelete(&delete_RawEvent);
      instance.SetDeleteArray(&deleteArray_RawEvent);
      instance.SetDestructor(&destruct_RawEvent);
      instance.SetStreamerFunc(&streamer_RawEvent);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::RawEvent*)
   {
      return GenerateInitInstanceLocal((::RawEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::RawEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr RawEvent::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *RawEvent::Class_Name()
{
   return "RawEvent";
}

//______________________________________________________________________________
const char *RawEvent::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::RawEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int RawEvent::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::RawEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void RawEvent::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::RawEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *RawEvent::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::RawEvent*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void RawEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class RawEvent.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      fAmp.Streamer(R__b);
      fTime.Streamer(R__b);
      fPeakHigh.Streamer(R__b);
      fPeakHighTime.Streamer(R__b);
      fPeakSum0.Streamer(R__b);
      fPeakSum.Streamer(R__b);
      fPeakSum_tail.Streamer(R__b);
      fPeakSum0_peak.Streamer(R__b);
      fPeakSumTime0.Streamer(R__b);
      fPeakSumTime1.Streamer(R__b);
      fPeakSumTime2.Streamer(R__b);
      {
         vector<Double_t> &R__stl =  fvAmp;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvTime;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakHigh;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakHighTime;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum0;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum_tail;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum0_peak;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSumTime0;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSumTime1;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSumTime2;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b >> fGraphSignal;
      R__b.CheckByteCount(R__s, R__c, RawEvent::IsA());
   } else {
      R__c = R__b.WriteVersion(RawEvent::IsA(), kTRUE);
      fAmp.Streamer(R__b);
      fTime.Streamer(R__b);
      fPeakHigh.Streamer(R__b);
      fPeakHighTime.Streamer(R__b);
      fPeakSum0.Streamer(R__b);
      fPeakSum.Streamer(R__b);
      fPeakSum_tail.Streamer(R__b);
      fPeakSum0_peak.Streamer(R__b);
      fPeakSumTime0.Streamer(R__b);
      fPeakSumTime1.Streamer(R__b);
      fPeakSumTime2.Streamer(R__b);
      {
         vector<Double_t> &R__stl =  fvAmp;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvTime;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakHigh;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakHighTime;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum0;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum_tail;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSum0_peak;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSumTime0;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSumTime1;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<Double_t> &R__stl =  fvPeakSumTime2;
         int R__n=(true) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<Double_t>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b << fGraphSignal;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void RawEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class RawEvent.
      TClass *R__cl = ::RawEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAmp", &fAmp);
      R__insp.InspectMember(fAmp, "fAmp.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &fTime);
      R__insp.InspectMember(fTime, "fTime.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakHigh", &fPeakHigh);
      R__insp.InspectMember(fPeakHigh, "fPeakHigh.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakHighTime", &fPeakHighTime);
      R__insp.InspectMember(fPeakHighTime, "fPeakHighTime.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSum0", &fPeakSum0);
      R__insp.InspectMember(fPeakSum0, "fPeakSum0.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSum", &fPeakSum);
      R__insp.InspectMember(fPeakSum, "fPeakSum.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSum_tail", &fPeakSum_tail);
      R__insp.InspectMember(fPeakSum_tail, "fPeakSum_tail.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSum0_peak", &fPeakSum0_peak);
      R__insp.InspectMember(fPeakSum0_peak, "fPeakSum0_peak.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSumTime0", &fPeakSumTime0);
      R__insp.InspectMember(fPeakSumTime0, "fPeakSumTime0.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSumTime1", &fPeakSumTime1);
      R__insp.InspectMember(fPeakSumTime1, "fPeakSumTime1.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPeakSumTime2", &fPeakSumTime2);
      R__insp.InspectMember(fPeakSumTime2, "fPeakSumTime2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvAmp", (void*)&fvAmp);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvAmp, "fvAmp.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvTime", (void*)&fvTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvTime, "fvTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakHigh", (void*)&fvPeakHigh);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakHigh, "fvPeakHigh.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakHighTime", (void*)&fvPeakHighTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakHighTime, "fvPeakHighTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSum0", (void*)&fvPeakSum0);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSum0, "fvPeakSum0.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSum", (void*)&fvPeakSum);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSum, "fvPeakSum.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSum_tail", (void*)&fvPeakSum_tail);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSum_tail, "fvPeakSum_tail.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSum0_peak", (void*)&fvPeakSum0_peak);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSum0_peak, "fvPeakSum0_peak.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSumTime0", (void*)&fvPeakSumTime0);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSumTime0, "fvPeakSumTime0.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSumTime1", (void*)&fvPeakSumTime1);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSumTime1, "fvPeakSumTime1.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fvPeakSumTime2", (void*)&fvPeakSumTime2);
      R__insp.InspectMember("vector<Double_t>", (void*)&fvPeakSumTime2, "fvPeakSumTime2.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNPoints", &fNPoints);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGraphSignal", &fGraphSignal);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_RawEvent(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::RawEvent : new ::RawEvent;
   }
   static void *newArray_RawEvent(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::RawEvent[nElements] : new ::RawEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_RawEvent(void *p) {
      delete ((::RawEvent*)p);
   }
   static void deleteArray_RawEvent(void *p) {
      delete [] ((::RawEvent*)p);
   }
   static void destruct_RawEvent(void *p) {
      typedef ::RawEvent current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_RawEvent(TBuffer &buf, void *obj) {
      ((::RawEvent*)obj)->::RawEvent::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::RawEvent

namespace ROOTDict {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<double>

/********************************************************
* /disk2/data/tmnguyen/testroottree/ForStudents/dataClasses/DataCint.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDataCint();

extern "C" void G__set_cpp_environmentDataCint() {
  G__cpp_reset_tagtableDataCint();
}
#include <new>
extern "C" int G__cpp_dllrevDataCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* RawEvent */
static int G__DataCint_231_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RawEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RawEvent[n];
     } else {
       p = new((void*) gvp) RawEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RawEvent;
     } else {
       p = new((void*) gvp) RawEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataCintLN_RawEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RawEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new RawEvent((const Int_t) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) RawEvent((const Int_t) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataCintLN_RawEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) RawEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) RawEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) RawEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      RawEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const RawEvent*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) RawEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) RawEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) RawEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) RawEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetAmp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakHigh());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakHighTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVAmp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakHigh());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakHighTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSum0());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSum_tail());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSum0_peak());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSumTime0());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSumTime1());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetVPeakSumTime2());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSum0());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSum_tail());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSum0_peak());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSumTime0());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSumTime1());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const RawEvent*) G__getstructoffset())->GetPeakSumTime2());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetAmp((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetTime((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvAmp((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvTime((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakHigh((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakHighTime((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSum0((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSum((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSum_tail((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSum0_peak((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSumTime0((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSumTime1((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetfvPeakSumTime2((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakHigh((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakHighTime((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSum0((long) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSum((long) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSum_tail((long) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSum0_peak((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSumTime0((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSumTime1((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetPeakSumTime2((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->PrintAmp((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->PrintTime((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->ProcessEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetTime((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetAmp((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakHigh((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakHighTime((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVAmp((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVTime((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakHigh((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakHighTime((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum0((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum_tail((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum0_peak((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSumTime0((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSumTime1((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSumTime2((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVAmpSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakHighSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_80(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum0Size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_81(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSumSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_82(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum_tailSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_83(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetVPeakSum0_peakSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_84(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSum0((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_85(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSum((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_86(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSum_tail((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_87(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSum0_peak((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_88(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSumTime0((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_89(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSumTime1((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_90(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((RawEvent*) G__getstructoffset())->GetPeakSumTime2((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_91(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((RawEvent*) G__getstructoffset())->GetGraphSignal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataCint_231_0_92(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawEvent*) G__getstructoffset())->SetGraphs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DataCint_231_0_94(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   RawEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new RawEvent(*(RawEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataCintLN_RawEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RawEvent G__TRawEvent;
static int G__DataCint_231_0_95(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (RawEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((RawEvent*) (soff+(sizeof(RawEvent)*i)))->~G__TRawEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (RawEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((RawEvent*) (soff))->~G__TRawEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* RawEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDataCint {
 public:
  G__Sizep2memfuncDataCint(): p(&G__Sizep2memfuncDataCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDataCint::*p)();
};

size_t G__get_sizep2memfuncDataCint()
{
  G__Sizep2memfuncDataCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDataCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDataCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DataCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DataCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__DataCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__DataCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* RawEvent */
static void G__setup_memvarRawEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DataCintLN_RawEvent));
   { RawEvent *p; p=(RawEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fAmp=",0,"array for raw amplitudes");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fTime=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakHigh=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakHighTime=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSum0=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSum=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSum_tail=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSum0_peak=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSumTime0=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSumTime1=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_TArrayD),-1,-1,4,"fPeakSumTime2=",0,"array for raw times");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvAmp=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakHigh=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakHighTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSum0=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSum=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSum_tail=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSum0_peak=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSumTime0=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSumTime1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,4,"fvPeakSumTime2=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,1,-1,G__defined_typename("Int_t"),-1,4,"fNPoints=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataCintLN_TGraph),-1,-1,4,"fGraphSignal=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataCintLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDataCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncRawEvent(void) {
   /* RawEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataCintLN_RawEvent));
   G__memfunc_setup("RawEvent",812,G__DataCint_231_0_1, 105, G__get_linked_tagnum(&G__DataCintLN_RawEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RawEvent",812,G__DataCint_231_0_2, 105, G__get_linked_tagnum(&G__DataCintLN_RawEvent), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 10 - npoints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DataCint_231_0_3, 85, G__get_linked_tagnum(&G__DataCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&RawEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DataCint_231_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&RawEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DataCint_231_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&RawEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DataCint_231_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&RawEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__DataCint_231_0_7, 85, G__get_linked_tagnum(&G__DataCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__DataCint_231_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__DataCint_231_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DataCint_231_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DataCint_231_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&RawEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DataCint_231_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&RawEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DataCint_231_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&RawEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DataCint_231_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&RawEvent::DeclFileLine) ), 0);
   G__memfunc_setup("Reset",515,G__DataCint_231_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAmp",574,G__DataCint_231_0_16, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__DataCint_231_0_17, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakHigh",1057,G__DataCint_231_0_18, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakHighTime",1456,G__DataCint_231_0_19, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVAmp",660,G__DataCint_231_0_20, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVTime",773,G__DataCint_231_0_21, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakHigh",1143,G__DataCint_231_0_22, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakHighTime",1542,G__DataCint_231_0_23, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum0",1116,G__DataCint_231_0_24, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum",1068,G__DataCint_231_0_25, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum_tail",1589,G__DataCint_231_0_26, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum0_peak",1628,G__DataCint_231_0_27, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumTime0",1515,G__DataCint_231_0_28, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumTime1",1516,G__DataCint_231_0_29, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumTime2",1517,G__DataCint_231_0_30, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum0",1030,G__DataCint_231_0_31, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum",982,G__DataCint_231_0_32, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum_tail",1503,G__DataCint_231_0_33, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum0_peak",1542,G__DataCint_231_0_34, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSumTime0",1429,G__DataCint_231_0_35, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSumTime1",1430,G__DataCint_231_0_36, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSumTime2",1431,G__DataCint_231_0_37, 68, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAmp",586,G__DataCint_231_0_38, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - a i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTime",699,G__DataCint_231_0_39, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvAmp",806,G__DataCint_231_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvTime",919,G__DataCint_231_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakHigh",1289,G__DataCint_231_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakHighTime",1688,G__DataCint_231_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSum0",1262,G__DataCint_231_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSum",1214,G__DataCint_231_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSum_tail",1735,G__DataCint_231_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSum0_peak",1774,G__DataCint_231_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSumTime0",1661,G__DataCint_231_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSumTime1",1662,G__DataCint_231_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetfvPeakSumTime2",1663,G__DataCint_231_0_50, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakHigh",1069,G__DataCint_231_0_51, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakHighTime",1468,G__DataCint_231_0_52, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSum0",1042,G__DataCint_231_0_53, 121, -1, -1, 0, 2, 1, 1, 0, 
"l - - 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSum",994,G__DataCint_231_0_54, 121, -1, -1, 0, 2, 1, 1, 0, 
"l - - 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSum_tail",1515,G__DataCint_231_0_55, 121, -1, -1, 0, 2, 1, 1, 0, 
"l - - 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSum0_peak",1554,G__DataCint_231_0_56, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSumTime0",1441,G__DataCint_231_0_57, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSumTime1",1442,G__DataCint_231_0_58, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPeakSumTime2",1443,G__DataCint_231_0_59, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - t i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintAmp",811,G__DataCint_231_0_60, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintTime",924,G__DataCint_231_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ProcessEvent",1249,G__DataCint_231_0_62, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__DataCint_231_0_63, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAmp",574,G__DataCint_231_0_64, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakHigh",1057,G__DataCint_231_0_65, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakHighTime",1456,G__DataCint_231_0_66, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVAmp",660,G__DataCint_231_0_67, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVTime",773,G__DataCint_231_0_68, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakHigh",1143,G__DataCint_231_0_69, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakHighTime",1542,G__DataCint_231_0_70, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum0",1116,G__DataCint_231_0_71, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum",1068,G__DataCint_231_0_72, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum_tail",1589,G__DataCint_231_0_73, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum0_peak",1628,G__DataCint_231_0_74, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumTime0",1515,G__DataCint_231_0_75, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumTime1",1516,G__DataCint_231_0_76, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumTime2",1517,G__DataCint_231_0_77, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVAmpSize",1071,G__DataCint_231_0_78, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakHighSize",1554,G__DataCint_231_0_79, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum0Size",1527,G__DataCint_231_0_80, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSumSize",1479,G__DataCint_231_0_81, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum_tailSize",2000,G__DataCint_231_0_82, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVPeakSum0_peakSize",2039,G__DataCint_231_0_83, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum0",1030,G__DataCint_231_0_84, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum",982,G__DataCint_231_0_85, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum_tail",1503,G__DataCint_231_0_86, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSum0_peak",1542,G__DataCint_231_0_87, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSumTime0",1429,G__DataCint_231_0_88, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSumTime1",1430,G__DataCint_231_0_89, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeakSumTime2",1431,G__DataCint_231_0_90, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGraphSignal",1392,G__DataCint_231_0_91, 85, G__get_linked_tagnum(&G__DataCintLN_TGraph), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGraphs",913,G__DataCint_231_0_92, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("RawEvent", 812, G__DataCint_231_0_94, (int) ('i'), G__get_linked_tagnum(&G__DataCintLN_RawEvent), -1, 0, 1, 1, 1, 0, "u 'RawEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~RawEvent", 938, G__DataCint_231_0_95, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDataCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDataCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDataCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DataCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TArrayD = { "TArrayD" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__DataCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__DataCintLN_RawEvent = { "RawEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDataCint() {
  G__DataCintLN_TClass.tagnum = -1 ;
  G__DataCintLN_TBuffer.tagnum = -1 ;
  G__DataCintLN_TMemberInspector.tagnum = -1 ;
  G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DataCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DataCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DataCintLN_TGraph.tagnum = -1 ;
  G__DataCintLN_TArrayD.tagnum = -1 ;
  G__DataCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__DataCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__DataCintLN_RawEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDataCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DataCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TGraph);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TArrayD);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__DataCintLN_TMatrixTBaselEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataCintLN_RawEvent),sizeof(RawEvent),-1,34048,(char*)NULL,G__setup_memvarRawEvent,G__setup_memfuncRawEvent);
}
extern "C" void G__cpp_setupDataCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDataCint()");
  G__set_cpp_environmentDataCint();
  G__cpp_setup_tagtableDataCint();

  G__cpp_setup_inheritanceDataCint();

  G__cpp_setup_typetableDataCint();

  G__cpp_setup_memvarDataCint();

  G__cpp_setup_memfuncDataCint();
  G__cpp_setup_globalDataCint();
  G__cpp_setup_funcDataCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDataCint();
  return;
}
class G__cpp_setup_initDataCint {
  public:
    G__cpp_setup_initDataCint() { G__add_setup_func("DataCint",(G__incsetup)(&G__cpp_setupDataCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDataCint() { G__remove_setup_func("DataCint"); }
};
G__cpp_setup_initDataCint G__cpp_setup_initializerDataCint;

