/********************************************************************
* /disk2/data/tmnguyen/testroottree/ForStudents/dataClasses/DataCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /disk2/data/tmnguyen/testroottree/ForStudents/dataClasses/DataCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataCint();
extern void G__cpp_setup_inheritanceDataCint();
extern void G__cpp_setup_typetableDataCint();
extern void G__cpp_setup_memvarDataCint();
extern void G__cpp_setup_globalDataCint();
extern void G__cpp_setup_memfuncDataCint();
extern void G__cpp_setup_funcDataCint();
extern void G__set_cpp_environmentDataCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/disk2/data/tmnguyen/testroottree/ForStudents/dataClasses/RawEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataCintLN_TClass;
extern G__linked_taginfo G__DataCintLN_TBuffer;
extern G__linked_taginfo G__DataCintLN_TMemberInspector;
extern G__linked_taginfo G__DataCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__DataCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DataCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DataCintLN_TGraph;
extern G__linked_taginfo G__DataCintLN_TArrayD;
extern G__linked_taginfo G__DataCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DataCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DataCintLN_RawEvent;

/* STUB derived class for protected member access */
